package tqs.Assignment;

// Generated by Selenium IDE

import static org.junit.jupiter.api.Assertions.*;

import static org.hamcrest.MatcherAssert.assertThat;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class TestWithSelenium {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void hw() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1920, 1040));
    driver.findElement(By.id("city")).click();
    driver.findElement(By.id("city")).sendKeys("aveiro");
    driver.findElement(By.id("city")).sendKeys(Keys.ENTER);
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("aveiro"));
    driver.findElement(By.cssSelector(".button_back")).click();
    driver.findElement(By.id("city")).click();
    driver.findElement(By.id("city")).sendKeys("aveiro");
    driver.findElement(By.id("city")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".button_back")).click();
    driver.findElement(By.id("city")).click();
    driver.findElement(By.id("city")).sendKeys("aveiro");
    driver.findElement(By.id("city")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".button_back")).click();
    driver.findElement(By.id("city")).click();
    driver.findElement(By.id("city")).sendKeys("cache");
    driver.findElement(By.id("city")).sendKeys(Keys.ENTER);
    assertThat(driver.findElement(By.id("hits")).getText(), is("2"));
    assertThat(driver.findElement(By.id("misses")).getText(), is("1"));
    assertThat(driver.findElement(By.id("requests")).getText(), is("3"));
    driver.findElement(By.cssSelector(".button_back")).click();
  }
}
